services:
  my-server:
    build: . #현재 경로에 있는 이미지를 기반으로 Dockerfile 띄울거임
    ports:
      - 8080:8080
    image: finnol-server:latest
#    depends_on:
#      mongodb: #서비스 이름
#        condition: service_healthy

#  mongodb:
#    image: mongo:latest
#    environment:
#      MONGO_INITDB_DATABASE: pinnol
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 1234
#    ports:
#      - "27017:27017"
#    healthcheck: #헬스체크 방식
#      test: ["CMD","mongosh","--quiet","--eval","db.adminCommand('ping')"]
#      interval: 5s
#      retries: 10
