version: '3.8'

services:
  finnol-server:
    build:
      context: . # Dockerfile이 있는 경로
    image: finnol-server:latest
    container_name: finnol-server
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATA_REDIS_HOST=redis #Redis 컨테이너 이름을 호스트로 지정
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis #Redis가 먼저 올라오도록 설정

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server","--appendonly","yes"]

volumes:
  redis-data: