spring:
  data:
    mongodb:
      uri: ${DEVELOP_MONGODB_URL}   # 개발용 MongoDB URI
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_LOCAL_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email


logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: WARN

custom:
  frontend:
    deploy:
      url: ${OAUTH2_SUCCESS_LOCAL_URL}

