spring:
  application:
    name: pinnol-be
  config:
    import: optional:file:.env[.properties]
  jackson:
    time-zone: Asia/Seoul

server:
  tomcat:
    keep-alive-timeout: 180s
    max-threads: 200
    max-keep-alive-requests: 100

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: WARN

cloud:
  aws:
    s3:
      bucket: finnol-image
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${S3_AWS_ACCESS_KEY_ID}
      secretKey: ${S3_AWS_SECRET_ACCESS_KEY}

myapp:
  fastApi:
    endpoint: ${RAG_URL}

jwt:
  secret: ${JWT_SECRET}

payments:
  toss:
    secret-key: ${PAYMENT_SECRET_KEY}
    success-url: http://localhost:8080/success
    fail-url: http://localhost:8080/fail
    original-url: https://api.tosspayments.com/v1/payments/
#    client-key: ${PAYMENT_CLIENT_KEY}
